apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
   - name: busybox
     image: busybox42/alpine-pod:latest
     volumeMounts:
       - mountPath: /mnt/mydir
         name: mypvc
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: test-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-filestore
  resources:
    requests:
      storage: 1Ti
