apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
   - name: stress
     imagePullPolicy: Always
     image: gcr.io/saikatroyc-test/stress:v1
     args:
       - "--mem-alloc-size=1Mi"
       - "--mem-alloc-sleep=20s"
       - "--mem-total=20Mi"
     resources:
      requests:
        memory: "9Mi"
      limits:
        memory: "9Mi"
     volumeMounts:
       - mountPath: /mnt/mydir
         name: mypvc
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: test-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-filestore
  resources:
    requests:
      storage: 1Ti
